// List of custom colors defined in global.css
export const CUSTOM_COLORS = [
  'rosewater',
  'flamingo',
  'pink',
  'mauve',
  'red',
  'maroon',
  'peach',
  'yellow',
  'green',
  'teal',
  'sky',
  'sapphire',
  'blue',
  'lavender',
  'text',
  'subtext-1',
  'subtext-0',
  'overlay-2',
  'overlay-1',
  'overlay-0',
  'surface-2',
  'surface-1',
  'surface-0',
  'base',
  'mantle',
  'crust',
] as const
export type CustomColorsType = typeof CUSTOM_COLORS[number]
